name: 'node_modules for project'
description: 'Install and Cache node_modules'
runs:
  using: 'composite'
  steps:
    - name: Get repo code
      uses: actions/checkout@v5.0.0
    - name: Cache deps
      uses: actions/cache@v4.3.0
      with:
        path: ~/.npm
        key: node-modules-deps-${{ hashFiles('**/package-lock.json') }}
    - name: Install dependencies
      run: npm ci
      shell: bash
