name: 'node_modules for project'
description: 'Install and Cache node_modules'
inputs:
  caching:
    required: false
    description: "enable or disable caching"
    default: 'true'
runs:
  using: 'composite'
  steps:
    - name: Cache deps
      if: inputs.caching == 'true'
      uses: actions/cache@v4.3.0
      with:
        path: ~/.npm
        key: node-modules-deps-${{ hashFiles('**/package-lock.json') }}
    - name: Install dependencies
      run: npm ci
      shell: bash
